name: Kernel Build (Z Flip 3 + KernelSU-Next + SUSFS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCH: arm64
      SUBARCH: arm64

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3
      with:
        submodules: true 

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev \
          libelf-dev build-essential libncurses-dev \
          cpio wget curl rsync

    - name: Download Android Toolchain
      run: |
        mkdir -p ~/toolchains
        curl -O https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r450784d.tar.gz
        tar -C ~/toolchains -xzf clang-r450784d.tar.gz
        echo "TOOLCHAIN=$(pwd)/toolchains/clang-r450784d" >> $GITHUB_ENV

    - name: Prepare KernelSU Integration
      run: |
        mkdir -p drivers
        touch drivers/Makefile
        touch drivers/Kconfig

        git clone https://github.com/rifsxd/KernelSU-Next.git
        cd KernelSU-Next
        git checkout next-susfs
        cd ..

        cp -r KernelSU-Next drivers/kernelsu

        echo 'obj-$(CONFIG_KSU) += kernelsu/' >> drivers/Makefile
        echo 'source "drivers/kernelsu/Kconfig"' >> drivers/Kconfig

    - name: Configure Kernel
      run: |
        export PATH=$TOOLCHAIN/bin:$PATH
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CC=clang

        make vendor/b2q_eur_openx_defconfig

        scripts/config --file .config --enable CONFIG_KSU
        scripts/config --file .config --enable CONFIG_SUSFS
        scripts/config --file .config --enable CONFIG_KPROBES
        scripts/config --file .config --enable CONFIG_HAVE_KPROBES
        scripts/config --file .config --enable CONFIG_KPROBE_EVENTS

        yes "" | make olddefconfig

    - name: Build Kernel
      run: |
        export PATH=$TOOLCHAIN/bin:$PATH
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CC=clang
        make -j$(nproc)

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: |
          arch/arm64/boot/Image.gz
          arch/arm64/boot/Image.gz-dtb
          arch/arm64/boot/dtbo.img

    - name: Upload .config
      uses: actions/upload-artifact@v4
      with:
        name: kernel-config
        path: .config
